### Оглавление
1. [Задача 1](#task1)
2. [Задача 2](#task2)
3. [Задача 3](#task3)
4. [Задача 4](#task4)


## Задача 1
<a id='task1'></a>
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [34]:
import numpy as np


In [30]:
N = input('Введите число: ')
x = np.arange (int(N))
x[::-1] 


Введите число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задача 2
<a id='task2'></a>
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [31]:
np.diag(x)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [32]:
b = np.asarray(x)
print(sum(b))

45


## Задача 3
<a id='task3'></a>
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [40]:
M = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
V = np.array([4, 12, -3])
np.linalg.solve(M, V)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задача 4
<a id='task4'></a>

In [45]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [5]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [48]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [51]:
for rec in users_stats:
    print (cosine(rec, next_user_stats))
    

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
